version: '3.4'

services:
  booky.api:
    image: ${DOCKER_REGISTRY-}bookyapi
    container_name: Booky.Api
    build:
      context: .
      dockerfile: src/Booky.Api/Dockerfile
    depends_on:
      - booky-db

  booky-db:
    image: postgres:latest
    container_name: Booky.db
    environment:
      - POSTGRES_DB=booky
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/posgresql/data
    ports:
      - 5432:5432
  
  bookify-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: Bookify.Identity
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files/bookify-realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - 18080:8080
 
  bookify-seq:
    image: datalust/seq:latest
    container_name: Bookify.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
  
  bookify-redis:
    image: redis:latest
    container_name: Bookify.Redis
    restart: always
    ports:
      - '6379:6379'

